---
title: "Consort"
author: 
date: "Last Updated: 12/15/2020"
output: 
  html_document:
    theme: flatly
    toc: True
    toc_float: True
---
```{r load-packages, echo=FALSE, warning=FALSE, include=FALSE, cache=FALSE}

library(magrittr)
library(codified)
library(rlang)
library(epiDisplay)
library(tibble)
library(tidyr)
library(checkmate)
library(testthat)
library(cowplot)
library(readxl)
library(knitr)
library(formattable)
library(ggpubr)
library(frequency)
library(plotly)
library(emmeans)
library(kableExtra)
library(papaja)
library(kableExtra)
library(dplyr)
library(RColorBrewer)
library(tidyverse)
library(ggformula)
library(lubridate)
library(plyr)
library(readr)
library(dplyr)
library(haven)
library(RColorBrewer)
library(ggplot2)
library(DiagrammeR)
library(DiagrammeRsvg)
library(rsvg)
library(reshape2)
library(skimr)
library(here)
knitr::opts_chunk$set(echo = TRUE)
options(knitr.table.format = "html", knitr.kable.NA = '') 
```

```{r, echo=FALSE}
htmltools::img(src = knitr::image_uri("/Users/akunerth/Dropbox (University of Oregon)/SEAL R01/_Remote SEAL/rSEAL_Dashboard/seallogo.jpg"), 
               alt = 'logo', 
               style = 'position:absolute; top:0; right:0; padding:10px;width: 128px; height: 128px')
```

```{r DK Log variable setup, echo = FALSE, message=FALSE}
#DK Data
DKdata <- data.frame(read.csv(file = '/Volumes/psy-ctn/psy-ctn/SNAPLab/SNAP Projects/SEAL/00_rSEAL/02_rSEAL_Data/PreStudy/DK_Log/Raw_Data/RSEALDKLog_DATA.csv'))
SubInfo <- data.frame(read.csv(file = '/Volumes/psy-ctn/psy-ctn/SNAPLab/SNAP Projects/SEAL/00_rSEAL/02_rSEAL_Data/PreStudy/Subject_Database/Raw_Data/RSEALSubjectDatabase_DATA.csv'))
DKParsedData <- select(DKdata, rseal_dkid,rseal_dklog_006:rseal_dk_log_complete )
```

DRAFT - Reworking value assignments/definitions

```{r Consort Diagram, echo = FALSE, message=FALSE}
#Consort Diagram Assign Variables
TotalRecruit <-nrow(DKParsedData)
Interested <- length(which(DKParsedData$rseal_dklog_009==1))
NotInterested <- length(which(DKParsedData$rseal_dklog_009==0))
NotDetermined <- TotalRecruit - (sum(Interested,NotInterested))
Eligible <- length(which(DKParsedData$rseal_dklog_038==1))
NoEligible <- length(which(DKParsedData$rseal_dklog_038==0))
Unver <- length(which(DKParsedData$rseal_dk_log_complete==1))
IntroSched <-nrow(SubInfo)
IntroComp <- length(which(SubInfo$rseal_subj_001==1))
IntroNoVerComp <- sum(is.na(SubInfo$rseal_subj_001))
Wave1NoComp <- length(which(SubInfo$rseal_subj_008==2))
Wave1Comp <- length(which(SubInfo$rseal_subj_027___1==1))
Wave2NoComp <- length(which(SubInfo$rseal_subj_008==3))
Wave2Comp <- length(which(SubInfo$rseal_subj_027___2==1))
IntervNoComp <- length(which(SubInfo$rseal_subj_008==3))
Wave3NoComp <- length(which(SubInfo$rseal_subj_008==4))
Wave3Comp <- length(which(SubInfo$rseal_subj_027___3==1))
IntervComp <- sum(SubInfo$rseal_subj_032 != "")
Consented <- sum(SubInfo$rseal_subj_002 != "")
InWave1 <-Consented-Wave1Comp
NoEnroll <- Eligible-Consented
NoContact <- sum(SubInfo$rseal_subj_026 != "")
NoReach <- NotDetermined-NoContact

grViz("digraph {
graph[rankdir=TD]
node[shape = rectangle, style = filled, fontsize = 20]
subgraph cluster_1 {
  graph[shape = rectangle, fontsize = 28, face = 'bold']
  style = rounded
  bgcolor = Gold
  
  label = < <font> <b>Pre-Consent</b> </font> >
  node[shape = rectangle, fillcolor = LemonChiffon, margin = 0.25]
  A [label = '@@1']
  B [label = '@@2']
  C [label = '@@3']
  D [label = '@@4', href='./Sources.html']
  F [label = '@@5']
  R [label = '@@6']
  S [label = '@@18']
  T [label = '@@9']
  U [label = '@@19']
  V [label = '@@20']
}
subgraph cluster_2 {
  graph[shape = rectangle, fontsize = 28]
  style = rounded
  bgcolor = Tomato
  
  label = < <font> <b>Consented</b> </font> >
  node[shape = rectangle, fillcolor = MistyRose, margin = 0.25 ]
  L [label = '@@11']
  K [label = '@@10']
  M [label = '@@12']
  N [label = '@@13']
  O [label = '@@14']
  P [label = '@@15']
  Q [label = '@@16']
}
A->B; A->D;A->R;R->U;R->V;
B->C; B->F;
C->T;C->S;
S->K;
K->M; S->L;
M->O;K->N;
O->Q; M->P;
}

#Define Labels
[1]: paste0('Total in DK Log (n = ', TotalRecruit, ')')
[2]: paste0('Total Interested (n = ', Interested, ')')
[3]: paste0('Total Eligible (n = ', Eligible, ')')
[4]: paste0('Not Interested (n = ', NotInterested, ')')
[5]: paste0('Total Not Eligible (n = ', NoEligible, ')')
[6]: paste0('Not Determined (n = ', NotDetermined, ')')
[7]: paste0('Intro Call Scheduled (n = ', IntroSched, ')')
[8]: paste0('Intro Call Complete (n = ', IntroComp, ')')
[9]: paste0('Eligible, But Not Enrolled (n = ', NoEnroll, ')')
[10]:paste0('Wave 1 Assessment Complete (n = ', Wave1Comp, ')')
[11]:paste0('Wave 1 Dropout (n = ', Wave1NoComp, ')')
[12]:paste0('Intervention Complete (n = ', IntervComp, ')')
[13]:paste0('Intervention Dropout (n = ', IntervNoComp, ')')
[14]:paste0('Wave 2 Complete (n = ', Wave2Comp, ')')
[15]:paste0('Wave 2 Dropout (n = ', Wave2NoComp, ')')
[16]:paste0('Wave 3 Complete (n = ', Wave3Comp, ')')
[17]:paste0('Wave 3 Dropout (n = ', Wave3NoComp, ')')
[18]: paste0('Enrolled (n = ', Consented, ')')
[19]: paste0('Not Contacted Yet (n = ', NoContact, ')')
[20]: paste0('Unable to Reach (n = ', NoReach, ')')
")
```

