---
title: "Current Enrollment"
author: 
date: "Last Updated: 1/17/2021"
output: 
  html_document:
    theme: flatly
    toc: TRUE
    toc_float: TRUE
---

```{r load-packages, echo=FALSE, warning=FALSE, include=FALSE, cache=FALSE}

library(magrittr)
library(codified)
library(rlang)
library(epiDisplay)
library(tibble)
library(tidyr)
library(checkmate)
library(testthat)
library(cowplot)
library(readxl)
library(knitr)
library(formattable)
library(ggpubr)
library(frequency)
library(plotly)
library(emmeans)
library(kableExtra)
library(papaja)
library(kableExtra)
library(dplyr)
library(RColorBrewer)
library(tidyverse)
library(ggformula)
library(lubridate)
library(plyr)
library(readr)
library(dplyr)
library(haven)
library(RColorBrewer)
library(ggplot2)
library(DiagrammeR)
library(DiagrammeRsvg)
library(rsvg)
library(reshape2)
library(skimr)
library(here)
knitr::opts_chunk$set(echo = TRUE)
options(knitr.table.format = "html", knitr.kable.NA = '') 
```


```{r Read in Files and set-up columns, echo = FALSE, warning=FALSE, message=FALSE}
#Read in Masterfile
masterfile <- data.frame(read_sav(file = '~/Dropbox (University of Oregon)/SEAL R01/_Remote SEAL/rSEAL_Data/masterfile.sav'))

  

#Create Frequency Table with completion Variables

Enrollment <- masterfile %>% select(RSID, Survey1Start, Survey2Start, PDR2Start, PDR3Start, rSEAL.C1.LDL.003, rSEAL.C1.LDL.029,Survey3Start, Survey4Start, PDR5Start, PDR6Start, rSEAL.C2.LDL.003, rSEAL.C2.LDL.029)

Enrollment$rSEAL.C1.LDL.003[Enrollment$rSEAL.C1.LDL.003 == ""] <- NA
Enrollment$rSEAL.C1.LDL.029[Enrollment$rSEAL.C1.LDL.029 == ""] <- NA
Enrollment$rSEAL.C2.LDL.003[Enrollment$rSEAL.C2.LDL.003 == ""] <- NA
Enrollment$rSEAL.C2.LDL.029[Enrollment$rSEAL.C2.LDL.029 == ""] <- NA

```


<center>
**Wave 1 Participant Completion ** 
<center>

:::: {style="display: flex;"}

::: {}
```{r SEAL Enrollment Counts, echo = FALSE, fig.width=5, fig.height=4, message=FALSE, warning=FALSE}
#par(mar = c(4, 4, .2, .1))

#library(lubridate)
#Survey1Start <- as.Date(masterfile$Survey1Start, "%Y/%m/%d %H:%M:%S")
#Survey2Start <- as.Date(masterfile$Survey1Start, "%Y/%m/%d %H:%M:%S")

#Complete <- masterfile %>%
  #dplyr::mutate(month = format(Survey1Start, "%m")) %>%
  #dplyr::group_by(month) %>%
  #dplyr::summarize(Count = n())
 
  #kable(Complete,
        #col.names = c("Month","Count")) %>%
        #kable_minimal()

```

```{r SEAL Wave Progression, echo = FALSE, fig.width=5, fig.height=4, message=FALSE, warning=FALSE}
par(mar = c(4, 4, .2, .1))

# Format dates

Enrollment$Survey1Start <- as.Date(Enrollment$Survey1Start, "%Y/%m/%d")
Enrollment$Survey2Start <- as.Date(Enrollment$Survey2Start, "%Y/%m/%d")
Enrollment$PDR2Start <- as.Date(Enrollment$PDR2Start, "%Y/%m/%d")
Enrollment$PDR3Start <- as.Date(Enrollment$PDR3Start, "%Y/%m/%d")
#Enrollment$rSEAL.C1.LDL.003 <- as.Date(Enrollment$rSEAL.C1.LDL.003, "%Y/%m/%d")
#Enrollment$rSEAL.C1.LDL.029 <- as.Date(Enrollment$rSEAL.C1.LDL.029, "%Y/%m/%d")

#Classify Tests
Survey1Completion <- Enrollment$Survey1Completion <- ifelse(Enrollment$Survey1Start > "2020-07-01", "Complete", "Incomplete")
Survey2Completion <- Enrollment$Survey2Completion <- ifelse(Enrollment$Survey2Start > "2020-07-01", "Complete", "Incomplete")
PDR2Completion <- Enrollment$PDR2Completion <- ifelse(Enrollment$PDR2Start > "2020-07-01", "Complete", "Incomplete")
PDR3Completion <- Enrollment$PDR3Completion<- ifelse(Enrollment$PDR3Start > "2020-07-01", "Complete", "Incomplete")
LENAD1DiaryCompletion <- Enrollment$LENAD1DiaryCompletion <- ifelse(Enrollment$rSEAL.C1.LDL.003 > "2020-07-01", "Complete", "Incomplete")
LENAD2DiaryCompletion <- Enrollment$LENAD2DiaryCompletion<- ifelse(Enrollment$rSEAL.C1.LDL.029 > "2020-07-01", "Complete", "Incomplete")

Wave1_Progression <- Enrollment %>%
  dplyr::mutate(month = format(Survey1Start, "%m")) %>%
  dplyr::group_by(Survey1Completion, Survey2Completion, PDR2Completion, PDR3Completion, LENAD1DiaryCompletion, LENAD2DiaryCompletion) %>%
  dplyr::summarize(Count = n())
 
  kable(Wave1_Progression,
        col.names = c("Survey 1","Survey 2","PDR 2", "PDR 3", "LENA D1 Diary", "LENA D2 Diary", "Number Complete")) %>%
        kable_minimal()
```


```{r SEAL Test Counts 1, echo = FALSE, fig.width=5, fig.height=4, message=FALSE, warning=FALSE}
par(mar = c(4, 4, .2, .1))

#Counts of Variables
Survey1Start <- as.character(Enrollment$Survey1Start)
Survey1Delinquent <- sum(is.na(Enrollment$Survey1Start))
Survey1Complete <- length(Survey1Start) - Survey1Delinquent

Survey2Start <- as.character(Enrollment$Survey2Start)
Survey2Delinquent <- sum(is.na(Enrollment$Survey2Start))
Survey2Complete <- length(Survey2Start) - Survey2Delinquent

PDR2Start <- as.character(Enrollment$PDR2Start)
PDR2Delinquent <- sum(is.na(Enrollment$PDR2Start))
PDR2Complete <- length(PDR2Start) - Survey2Delinquent

PDR3Start <- as.character(Enrollment$PDR3Start)
PDR3Delinquent <- sum(is.na(Enrollment$PDR3Start))
PDR3Complete <- length(PDR3Start) - PDR3Delinquent

LENAD1Start <- as.character(Enrollment$rSEAL.C1.LDL.003)
LENAD1Delinquent <- sum(is.na(Enrollment$rSEAL.C1.LDL.003))
LENAD1Complete <- length(LENAD1Start) - LENAD1Delinquent

LENAD2Start <- as.character(Enrollment$rSEAL.C1.LDL.029)
LENAD2Delinquent <- sum(is.na(Enrollment$rSEAL.C1.LDL.029))
LENAD2Complete <- length(LENAD2Start) - LENAD2Delinquent


# Create data
data <- data.frame(
  Wave1=c("Survey 1","Survey 2","PDR 2","PDR 3","LENA Day 1 Diary", "LENA Day 2 Diary") ,  
  value=c(Survey1Complete,Survey2Complete,PDR2Complete,PDR3Complete,LENAD1Complete, LENAD2Complete)
  )

tbl <- kbl(data, col.names = c("Wave1","Counts")) %>%
  kable_styling( bootstrap_options = "striped", full_width = F, position = "float_left", font_size = 16)
tbl


```
:::

::::
