---
title: "FamTracker - Research"
author: 
date: "Last Updated: 12/15/2020"
output: 
  html_document:
    theme: flatly
---
```{r load-packages, echo=FALSE, warning=FALSE, include=FALSE, cache=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(knitr)
options(digits=1)
library(ggpubr)
library(plotly)
library(emmeans)
library(papaja)
library(ggpubr)
library(kableExtra)
library(descr)
library(dplyr)
library(magick)
library(tidyverse)
library(ggformula)
library(lubridate)
library(janitor)
library(plyr)
library(tigerstats)
library(plotrix)
library(RColorBrewer)
options(knitr.table.format = "html", knitr.kable.NA = '') 
```

```{r, echo=FALSE}
htmltools::img(src = knitr::image_uri("/Users/akunerth/Dropbox (University of Oregon)/SEAL R01/_Remote SEAL/rSEAL_Dashboard/seallogo.jpg"), 
               alt = 'logo', 
               style = 'position:absolute; top:0; right:0; padding:10px;width: 128px; height: 128px')
```

<style type="text/css">
.main-container {
  max-width: 1800px;
  margin-left: auto;
  margin-right: auto;
}
</style>

<iframe src ="https://dat-snaplab.shinyapps.io/RecruitmentPage/" style="border: none; width: 1500px; height: 1000px;"/>
</iframe>
