---
title: "Reports"
author: 
date: "Last Updated: 1/21/2020"
output: 
  html_document:
    theme: flatly
    toc: TRUE
    css: columns.css
---

```{r load-packages, echo=FALSE, warning=FALSE, include=FALSE, cache=FALSE}
library(magrittr)
library(codified)
library(rlang)
library(tibble)
library(tidyr)
library(checkmate)
library(testthat)
library(cowplot)
library(readxl)
library(knitr)
library(formattable)
library(ggpubr)
library(frequency)
library(plotly)
library(emmeans)
library(kableExtra)
library(papaja)
library(kableExtra)
library(dplyr)
library(RColorBrewer)
library(tidyverse)
library(ggformula)
library(lubridate)
library(plyr)
library(RColorBrewer)
library(ggplot2)
library(DiagrammeR)
library(DiagrammeRsvg)
library(rsvg)
library(reshape2)
library(skimr)
library(here)
knitr::opts_chunk$set(echo = TRUE)
options(knitr.table.format = "html", knitr.kable.NA = '') 
```


```{r Read in Files, echo = FALSE, warning=FALSE, message=FALSE}
#Enrollment Data
#Enrollment <- data.frame(read.csv(file = #'/Volumes/psy-ctn/psy-ctn/SNAPLab/SNAP Projects/SEAL/Data #Management/Enrollment_Table/Enrollment_Table15DEC2020_Rversion.csv#'))

#SEAL Numbers Data
#Numbers <- data.frame(read_xlsx('/Volumes/psy-ctn/psy-ctn/SNAPLab/#SNAP Projects/SEAL/Data #Management/Enrollment_Table/SEAL_OG_Numbers.xlsx','Current_Data'))

#rSEAL Manual Consent Data
Consents1 <- data.frame(read_xlsx('~/Dropbox (University of Oregon)/SEAL R01/_Remote SEAL/rSEAL_Data/rSEAL_manual_consents.xlsx', 'Sheet1'))

#rSEAL Test Consent Data
Consents2 <- data.frame(read_xlsx('~/Dropbox (University of Oregon)/SEAL R01/_Remote SEAL/rSEAL_Data/Consent_Test.xlsx', 'Sheet1'))

#Format Dates for Consent Data
Consents2$Informed.consent <- as.Date(Consents2$Informed.consent , "%m/%d/%Y")
Consents2$Staff.Signature <- as.Date(Consents2$Staff.Signature , "%m/%d/%Y")
#Numbers$ConsentDates <- as.Date(Numbers$ConsentDates , "%Y-%m-%d")

#Create new DataFrame for Consents

#ConsentNumbers <- data.frame("RSID" = Numbers$SLID,
                        #"Consent"= Numbers$ConsentDates)

Consents1 <- data.frame("RSID" = Consents1$RSID,
                        "InformedConsent"= Consents1$Informed.consent, 
                        "Recontact" = Consents1$Recontact,
                        "StaffSignature"= Consents1$Staff.Signature)

Consents2 <- data.frame("RSID" = Consents2$RSID,
                        "InformedConsent"= Consents2$Informed.consent, 
                        "Recontact" = Consents2$Recontact,
                        "StaffSignature"= Consents2$Staff.Signature)

CombinedConsents <- left_join(Consents1,Consents2)
library(dplyr)
CombinedConsents2 <- full_join(Consents1, Consents2)

#StudyType <- CombinedConsents2$StudyType <- #if(CombinedConsents2$Consent > "2019-06-01"){
#CombinedConsents2$StudyType = "SEAL"
#} else {
#CombinedConsents2$StudyType = "rSEAL"
#}

#StudyType <- CombinedConsents2$StudyType <- #ifelse(CombinedConsents2$InformedConsent > "2019-06-01", "rSEAL", #"NA")
```


<center>
**Counts of dyads for rSEAL.** 
<center>

::: {}
```{r SEAL Conditions Count, echo = FALSE, fig.width=5, fig.height=4, message=FALSE, warning=FALSE}
par(mar = c(4, 4, .2, .1))

#Condition <- as.numeric(as.character(Numbers$Condition))

ConsentCounts <- CombinedConsents2 %>%
  dplyr::group_by(InformedConsent) %>%
  dplyr::summarize(count = n())

ConsentCounts3 <- ConsentCounts %>%
    arrange(InformedConsent) %>%
    mutate(Cumulative = cumsum(count))

library(ggplot2)
library(dplyr)
library(plotly)
library(hrbrthemes)
p <- ConsentCounts3 %>%
  ggplot( aes(x=InformedConsent, y=Cumulative)) +
    geom_area(fill="#69b3a2", alpha=0.5) +
    geom_line(color="#69b3a2") +
    ylab("Dyad Count") +
    xlab("Time") +
    theme_ipsum()
p <- ggplotly(p)

ConsentCounts4 <- ConsentCounts3 %>%
  mutate(month = format(InformedConsent, "%m"), year = format(InformedConsent, "%Y")) %>%
  group_by(month, year)

ConsentCounts4$InformedConsent <- as.Date(ConsentCounts4$InformedConsent)
ConsentCounts5 <- ConsentCounts4 %>%
  group_by(month, year) %>%
  #summarize(sessions=sum(sessions)) %>%
  #print table steps by month by year
  #print (n=100) %>%
  #graph data by month by year
  ggplot(aes(x=month, y=Cumulative, fill = month)) + 
  geom_bar(position = "dodge", stat='identity') +
 facet_wrap(~year)
  

  #kable(ConsentCounts4,
   #     col.names = c("Month","Count", "Cumulative", "Month", "Year")) %>%
    #    kable_minimal()

```
:::
<center>
```{r SEAL Conditions Plot, echo = FALSE, fig.width=10, fig.height=4,, message=FALSE, warning=FALSE}
par(mar = c(4, 4, .2, .1))

p

ConsentCounts5
```
<center>
::: {}

::::

<center>
**Enrollment Table** 
TBD
<center>

:::: {style="display: flex;"}

::: {}

```{r SEAL Interventions Count, echo = FALSE, fig.width=5, fig.height=4, message=FALSE, warning=FALSE}
#par(mar = c(4, 4, .2, .1))

#Condition <- as.numeric(as.character(Numbers$Condition))

#IntvStart <- Numbers %>%
# dplyr::group_by(Condition, IntvStartMonth) %>%
 # dplyr::summarize(Count = n())

 # kable(IntvStart,
     #   col.names = c("Condition","Month/Year","Count")) %>%
     #   kable_minimal()

```
:::

::: {}
```{r SEAL Interventions Plot, echo = FALSE, fig.width=5, fig.height=4,, message=FALSE, warning=FALSE}
#par(mar = c(4, 4, .2, .1))

#ConditionsPlot <- ggplot(IntvStart, aes(x = IntvStartMonth, y = Count, fill #= Condition)) +
  #geom_col() +
 # facet_wrap(~Condition)+
 # theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 1))

#ConditionsPlot + labs(x = "Month/Year")
```
:::

::::
```{r NIH Table, echo = FALSE, message=FALSE, warning=FALSE,}

#library(magrittr)
#path <- system.file("/Volumes/psy-ctn/psy-ctn/SNAPLab/SNAP Projects/SEAL/Data #Management/Enrollment_Table/Enrollment_Table15DEC2020_Rversion.csv", package="codified")
#col_types <- readr::cols_only(
 # record_id = readr::col_integer(),
  #name_last = readr::col_character(),
  #dob       = readr::col_date(format = ""),
  #gender    = readr::col_integer(),
  #race      = readr::col_integer(),
  #ethnicity = readr::col_integer()
#)
#ds <- readr::read_csv("/Volumes/psy-ctn/psy-ctn/SNAPLab/SNAP Projects/SEAL/Data #Management/Enrollment_Table/Enrollment_Table15DEC2020_Rversion.csv") %>%
#  dplyr::mutate(
 #   gender     = as.character(gender),
  #  race       = as.character(race),
   # ethnicity  = as.character(ethnicity)
  #)
#ds %>% 
  #head(10) %>% 
  #knitr::kable(caption = "Observed Dataset (first ten rows)")
```

```{r NIH Table Gender Mapping, echo = FALSE, message=FALSE, warning=FALSE,}
#ds_lu_gender <- tibble::tribble(
 # ~input,   ~displayed            ,
  #"0"   ,  "Female"               , 
  #"1"   ,  "Male"                 ,
  #"U"   ,  "Unknown/Not Reported"
#)
#knitr::kable(ds_lu_gender, caption = "Gender Mapping")
```

```{r NIH Table Race Mapping, echo = FALSE, message=FALSE, warning=FALSE,}
#ds_lu_race <- tibble::tribble(
 # ~input , ~displayed                                   ,
  #"1"    , "American Indian/Alaska Native"              ,
  #"2"    , "Asian"                                      ,
  #"3"    , "Native Hawaiian or Other Pacific Islander"  ,
  #"4"    , "Black or African American"                  ,
  #"5"    , "White"                                      ,
  #"M"    , "More than One Race"                         ,
  #"6"    , "Unknown or Not Reported"
#)
#knitr::kable(ds_lu_race, caption = "Race Mapping")
```

```{r NIH Table Ethnicity Mapping, echo = FALSE, message=FALSE, warning=FALSE,}
#ds_lu_ethnicity <- tibble::tribble(
 # ~input,   ~displayed                      ,
  #"2"   ,  "Not Hispanic or Latino"         ,
  #"1"   ,  "Hispanic or Latino"             ,
  #"0"   ,  "Unknown/Not Reported Ethnicity"
#)
#knitr::kable(ds_lu_ethnicity, caption = "Ethnicity Mapping")
```

```{r NIH Table Mapped to Observed, echo = FALSE, message=FALSE, warning=FALSE,}
#ds_summary_long <- codified::table_nih_enrollment(
 # d              = ds,
  #d_lu_gender    = ds_lu_gender,
  #d_lu_race      = ds_lu_race,
  #d_lu_ethnicity = ds_lu_ethnicity
#)

#knitr::kable(ds_summary_long, caption = "Counts of Each Subgroup")
```


```{r NIH Table Conform to Cosmetics, echo = FALSE, message=FALSE, warning=FALSE}
#codified::table_nih_enrollment_pretty(
 # d              = ds,
  #d_lu_gender    = ds_lu_gender,
  #d_lu_race      = ds_lu_race,
  #d_lu_ethnicity = ds_lu_ethnicity
#)
```
